import "server-only";
import PDFDocument from "pdfkit";

export type StmtRow = { number: string; date: string; due: string; total: number; paid: number; balance: number };

const money = (n: number, c: string) => `${c} ${(Number(n) || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export async function generateStatementPdf(opts: {
  companyName: string; customer: string; currency: string; rows: StmtRow[]; outstanding: number; accent?: string;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 48 });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const accent = opts.accent || "#0064d9";
    const cur = opts.currency || "AED";
    const left = 48, right = 547;

    // Header
    doc.fillColor(accent).font("Helvetica-Bold").fontSize(20).text("STATEMENT OF ACCOUNT", left, 48, { align: "right", width: right - left });
    doc.fillColor("#1d2733").font("Helvetica-Bold").fontSize(13).text(opts.companyName, left, 52);
    doc.moveDown(1.4);
    doc.font("Helvetica").fontSize(10).fillColor("#5b6b7b");
    doc.text(`To:  ${opts.customer}`, left);
    doc.text(`Date:  ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}`, left);
    doc.moveDown(1);

    // Table header
    const cols = { date: left, num: 120, total: 250, paid: 350, bal: 447 };
    const w = { total: 90, paid: 90, bal: 100 };
    let y = doc.y + 4;
    doc.save().rect(left, y - 4, right - left, 22).fill("#16202c").restore();
    doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(9);
    doc.text("DATE", cols.date + 6, y + 2);
    doc.text("INVOICE", cols.num, y + 2);
    doc.text("TOTAL", cols.total, y + 2, { width: w.total, align: "right" });
    doc.text("PAID", cols.paid, y + 2, { width: w.paid, align: "right" });
    doc.text("BALANCE", cols.bal, y + 2, { width: w.bal, align: "right" });
    y += 24;

    // Rows
    doc.font("Helvetica").fontSize(9.5).fillColor("#1d2733");
    for (const r of opts.rows) {
      if (y > 760) { doc.addPage(); y = 60; }
      doc.fillColor("#1d2733").text(r.date || "—", cols.date + 6, y);
      doc.fillColor(accent).text(r.number, cols.num, y);
      doc.fillColor("#1d2733").text(money(r.total, cur), cols.total, y, { width: w.total, align: "right" });
      doc.fillColor("#5b6b7b").text(money(r.paid, cur), cols.paid, y, { width: w.paid, align: "right" });
      doc.fillColor(r.balance > 0 ? "#cc1919" : "#1d2733").font("Helvetica-Bold").text(money(r.balance, cur), cols.bal, y, { width: w.bal, align: "right" }).font("Helvetica");
      y += 18;
      doc.save().moveTo(left, y - 4).lineTo(right, y - 4).strokeColor("#eef1f5").lineWidth(0.5).stroke().restore();
    }
    if (opts.rows.length === 0) {
      doc.fillColor("#5b6b7b").text("No open invoices — account is settled.", left, y + 4);
      y += 22;
    }

    // Total outstanding
    y += 10;
    doc.save().rect(cols.total, y - 4, right - cols.total, 26).fill("#f6f9fb").restore();
    doc.fillColor("#5b6b7b").font("Helvetica-Bold").fontSize(10).text("TOTAL OUTSTANDING", cols.total, y + 3, { width: w.total + 6 });
    doc.fillColor(accent).fontSize(13).text(money(opts.outstanding, cur), cols.bal - 100, y + 1, { width: w.bal + 100, align: "right" });

    doc.font("Helvetica").fontSize(8).fillColor("#8a97a5").text("Generated by Xentral Books · " + opts.companyName, left, 800, { align: "center", width: right - left });
    doc.end();
  });
}
